# Generated by Django 3.2.8 on 2021-10-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='diaryEntryDate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='diaryEntryMessage',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='diaryEntryTitle',
            new_name='title',
        ),
    ]
