version: "3"
services:
    web:
        depends_on:
            - redis 
        build: .
        ports:
            - 8000:8000
        
        links:
        - redis
        
    redis:
        image: redis
        ports:
            - 6379:6379
