# Generated by Django 3.2.8 on 2021-10-15 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=500)),
                ('task_title', models.CharField(max_length=100)),
                ('issued_on', models.DateTimeField(auto_now=True)),
                ('task_deadline', models.DateTimeField()),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('task_type', models.SmallIntegerField(choices=[(0, 'pending_task'), (1, 'done_task'), (2, 'lazy_task')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
